// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzpUEZq-bMudjqX1cmLUKYwB7zxdjI7i4',
    appId: '1:759253446573:web:9c8882bc4849b9a8c63b24',
    messagingSenderId: '759253446573',
    projectId: 'yohomez',
    authDomain: 'yohomez.firebaseapp.com',
    storageBucket: 'yohomez.appspot.com',
    measurementId: 'G-W7F03BF895',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNcI4RpsqbgH1N7u5-Q3iQemUF7TIXlJY',
    appId: '1:759253446573:android:a739db460867dc3fc63b24',
    messagingSenderId: '759253446573',
    projectId: 'yohomez',
    storageBucket: 'yohomez.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0ZUZJYObOxFVNGVTNhAllvrk4Q_WMyP0',
    appId: '1:759253446573:ios:30e3811e8d400d0cc63b24',
    messagingSenderId: '759253446573',
    projectId: 'yohomez',
    storageBucket: 'yohomez.appspot.com',
    iosClientId: '759253446573-e03kufit5sp8oemt332jv4hdbbodqibk.apps.googleusercontent.com',
    iosBundleId: 'com.yohomez.yohomez',
  );
}
